# Puerto del servidor
server.port=8080

# --- CONFIGURACIÓN POSTGRESQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/RutasTuristicas
spring.datasource.username=postgres
spring.datasource.password=Ingeniero95*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- CONFIGURACIÓN HIBERNATE/JPA ---
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Propiedades adicionales PostgreSQL
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
