# Puerto en el que corre el servidor
server.port=8080

# --- CONFIGURACIÓN BASE DE DATOS (PostgreSQL) ---
# Descomentar estas líneas para usar PostgreSQL en producción
# spring.datasource.url=jdbc:postgresql://localhost:5422/turismo_db
# spring.datasource.username=postgres
# spring.datasource.password=admin123
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- CONFIGURACIÓN BASE DE DATOS LOCAL/PRUEBAS (H2 en memoria) ---
spring.datasource.url=jdbc:h2:mem:turismo_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar consola de H2 para depuración visual en /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# --- CONFIGURACIÓN DE HIBERNATE / JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Permitir el encuadre en H2 Console para navegadores modernos (Evita X-Frame-Options)
spring.headers.frame-options=disable
